backtesting:
  commission: 0.001
  initial_capital: 100000
  metrics:
  - total_return
  - sharpe_ratio
  - max_drawdown
  - win_rate
  - profit_factor
  - expectancy
  - calmar_ratio
  slippage: 0.0005
bybit:
  fees:
    funding_rate: 0.0001
    maker: 0.0002
    taker: 0.00055
  slippage:
    base: 0.0005
    market_impact_threshold: 0.01
data:
  end_date: '2025-06-16'
  interval_minutes: 15
  start_date: '2022-06-08'
  symbols:
  - BTCUSDT
  - ETHUSDT
  - BNBUSDT
  - SOLUSDT
  - XRPUSDT
  - AAVEUSDT
  - ADAUSDT
  - ALGOUSDT
  - APEUSDT
  - APTUSDT
  - ARBUSDT
  - ATOMUSDT
  - AVAXUSDT
  - AXSUSDT
  - CAKEUSDT
  - DOGEUSDT
  - DOTUSDT
  - DYDXUSDT
  - ENAUSDT
  - ENSUSDT
  - FARTCOINUSDT
  - GALAUSDT
  - GMTUSDT
  - GRIFFAINUSDT
  - HBARUSDT
  - ICPUSDT
  - JTOUSDT
  - LDOUSDT
  - LINKUSDT
  - LTCUSDT
  - MELANIAUSDT
  - NEARUSDT
  - OMUSDT
  - ONDOUSDT
  - OPUSDT
  - 1000PEPEUSDT
  - PNUTUSDT
  - POPCATUSDT
  - SUIUSDT
  - TAOUSDT
  - TIAUSDT
  - TONUSDT
  - TRBUSDT
  - TRUMPUSDT
  - TRXUSDT
  - TWTUSDT
  - UNIUSDT
  - WIFUSDT
  - ZEREBROUSDT
  - 1INCHUSDT
  test_ratio: 0.2
  train_ratio: 0.6
  val_ratio: 0.2
  walk_forward:
    step_size: 7
    test_window: 30
    training_window: 180
    validation_window: 30
database:
  database: crypto_trading
  host: localhost
  max_overflow: 20
  password: ruslan
  pool_size: 10
  port: 5555
  table: raw_market_data
  user: ruslan
ensemble:
  enabled: true
  models_count: 5
  rebalance_frequency: weekly
  voting_method: weighted_average
  weight_metric: sharpe_ratio
features:
  cross_asset:
  - btc_dominance_effect
  - sector_correlation
  - lead_lag_signals
  microstructure:
  - bid_ask_spread
  - order_book_imbalance
  - volume_weighted_price
  - trade_flow_toxicity
  technical:
  - name: sma
    periods:
    - 10
    - 20
    - 50
  - name: ema
    periods:
    - 12
    - 26
  - name: rsi
    period: 14
  - fast: 12
    name: macd
    signal: 9
    slow: 26
  - name: bollinger_bands
    period: 20
    std_dev: 2
  - name: atr
    period: 14
  - bins: 20
    name: volume_profile
  temporal:
  - hour_of_day
  - day_of_week
  - month_of_year
  - is_weekend
logging:
  handlers:
  - console
  - file
  level: INFO
  log_dir: experiments/logs
  tensorboard:
    enabled: true
    log_dir: experiments/tensorboard
  wandb:
    enabled: false
    entity: your-entity
    project: crypto-ai-trading
loss:
  name: mse
  params:
    reduction: mean
model:
  activation: gelu
  batch_norm: true
  batch_size: 128  # Увеличен для лучшей стабильности
  context_window: 96  # Увеличен для лучшего контекста
  d_ff: 512  # Увеличен размер feedforward
  d_model: 128  # Увеличена размерность модели
  dropout: 0.2  # Уменьшен dropout
  e_layers: 3  # Оптимальное количество слоев
  early_stopping_patience: 20  # Больше терпения
  epochs: 100  # Больше эпох с early stopping
  gradient_clip: 0.5  # Более агрессивный clipping
  individual: false
  input_size: 100
  learning_rate: 0.00001  # Еще больше уменьшен для предотвращения NaN
  min_delta: 0.0001  # Более чувствительный порог
  n_heads: 4
  name: PatchTST
  output_size: 1
  overfitting_threshold: 0.2  # Более строгий контроль
  patch_len: 16  # Увеличен размер патча
  target_variable: future_return_4  # Используем future_return_4 (доходность через 1 час для 15-мин данных)
  task_type: regression
  target_window: 1  # Предсказываем одно значение
  pred_len: 1  # Предсказываем одно значение
  stride: 8  # Увеличен шаг для меньшего перекрытия
  warmup_steps: 500  # Больше warmup шагов
  # Дополнительные параметры против переобучения
  label_smoothing: 0.1
  mixup_alpha: 0.2
  weight_noise: 0.01
  # Параметры для улучшенной версии PatchTST
  use_improvements: true  # Использовать улучшения из patchtst_improved
  feature_attention: true  # Использовать FeatureAttention
  multi_scale_patches: true  # Использовать многомасштабные патчи
optimizer:
  name: AdamW
  params:
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0.001
    amsgrad: true
performance:
  cache_dir: cache/
  cache_features: true
  data_parallel: true
  device: cuda
  mixed_precision: false
  num_workers: 2
  persistent_workers: false
  pin_memory: true
  prefetch_factor: 1
remote_server:
  direct_connection:
    host: 109.198.107.223
    key_path: ~/.ssh/id_rsa
    port: 48937
    user: root
  enabled: true
  ports:
    jupyter: 8888
    tensorboard: 6006
    web_ui: 8080
  python_path: /opt/conda/bin/python
  remote_path: /root/crypto_ai_trading
  ssh_alias: vast-current
  sync:
    exclude:
    - cache/
    - '*.pyc'
    - __pycache__/
    - .git/
    - logs/
    - models_saved/
    - experiments/runs/
    - .DS_Store
risk_management:
  max_concurrent_positions: 10
  max_positions_per_symbol: 1
  partial_close_sizes:
  - 40
  - 40
  - 20
  position_sizing:
    correlation_adjustment: true
    max_position_pct: 10.0
    max_risk_per_trade: 0.5
    method: kelly_criterion
  risk_reward_ratio: 3.0
  stop_loss_pct: 2.0
  take_profit_targets:
  - 1.5
  - 2.5
  - 4.0
  volatility_adjustment:
    altcoin_risk_multiplier: 0.7
    high_vol_multipliers:
    - 1.8
    - 3.0
    - 5.0
    high_vol_threshold: 3.0
    low_vol_multipliers:
    - 1.2
    - 2.0
    - 3.0
    low_vol_threshold: 1.5
    major_coins:
    - BTCUSDT
    - ETHUSDT
    - BNBUSDT
    major_risk_multiplier: 1.0
    meme_coin_risk_multiplier: 0.5
scheduler:
  name: ReduceLROnPlateau
  params:
    factor: 0.5
    min_lr: 1.0e-06
    mode: min
    patience: 5
    threshold: 0.0001
trading:
  max_daily_trades: 15
  max_positions: 5
  min_confidence_threshold: 0.65
  multiframe_confirmation: true
  rebalance_interval: 1h
validation:
  max_drawdown: 0.2
  min_sharpe_ratio: 1.5
  min_win_rate: 0.25
  statistical_tests:
  - sharpe_ratio_test
  - information_ratio
  - monte_carlo_permutation
