# Основная конфигурация проекта AI торговой системы

# Подключение к базе данных (адаптировано под вашу БД)
database:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5555}
  database: ${DB_NAME:crypto_trading}
  user: ${DB_USER:ruslan}
  password: ${DB_PASSWORD:ruslan}
  table: "raw_market_data"
  pool_size: 10
  max_overflow: 20

# Параметры данных
data:
  # Список торговых пар для анализа (из вашей БД)
  # Для первого запуска используем только топ-10 монет
  symbols: 
    - "BTCUSDT"
    - "ETHUSDT"
    - "BNBUSDT"
    - "SOLUSDT"
    - "XRPUSDT"
    - "ADAUSDT"
    - "DOTUSDT"
    - "LINKUSDT"
    - "AVAXUSDT"
    - "LTCUSDT"
  # Для загрузки всех символов используйте:
  # symbols: ["ALL"]
  
  # Временные параметры (адаптировано под ваши данные)
  start_date: "2022-06-08"
  end_date: "2025-06-16"
  interval_minutes: 15
  
  # Разделение данных
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  
  # Walk-forward параметры
  walk_forward:
    training_window: 180  # дней
    validation_window: 30
    test_window: 30
    step_size: 7  # дней

# Инженерия признаков
features:
  # Технические индикаторы
  technical:
    - name: "sma"
      periods: [10, 20, 50]
    - name: "ema"
      periods: [12, 26]
    - name: "rsi"
      period: 14
    - name: "macd"
      fast: 12
      slow: 26
      signal: 9
    - name: "bollinger_bands"
      period: 20
      std_dev: 2
    - name: "atr"
      period: 14
    - name: "volume_profile"
      bins: 20
  
  # Микроструктурные признаки
  microstructure:
    - "bid_ask_spread"
    - "order_book_imbalance"
    - "volume_weighted_price"
    - "trade_flow_toxicity"
  
  # Кросс-активные признаки
  cross_asset:
    - "btc_dominance_effect"
    - "sector_correlation"
    - "lead_lag_signals"
  
  # Временные признаки
  temporal:
    - "hour_of_day"
    - "day_of_week"
    - "month_of_year"
    - "is_weekend"

# Параметры модели PatchTST
model:
  name: "PatchTST"
  
  # Архитектура
  input_size: 100  # количество признаков
  patch_len: 16    # длина патча
  stride: 8        # шаг патча
  context_window: 96   # 24 часа - оптимально (для 15-мин данных)
  
  # Transformer параметры
  d_model: 256         # Увеличено для лучшего качества
  n_heads: 16          # Увеличено количество голов
  e_layers: 3          # encoder layers
  d_ff: 512            # feedforward dimension
  dropout: 0.1
  activation: "gelu"
  batch_norm: true     # Добавлена нормализация
  
  # Прогнозирование
  pred_len: 4          # прогноз на 4 шага (1 час)
  individual: false    # channel-independent
  
  # Обучение
  learning_rate: 0.0001   # Уменьшен для стабильности
  batch_size: 32
  epochs: 100
  early_stopping_patience: 10
  gradient_clip: 1.0
  warmup_steps: 1000      # Добавлен warmup

# Управление рисками (адаптировано под ваши настройки)
risk_management:
  # Основные параметры
  risk_reward_ratio: 3.0
  stop_loss_pct: 2.0                    # Реалистично для крипто
  take_profit_targets: [1.5, 2.5, 4.0]  # Меньше уровней, выше достижимость
  partial_close_sizes: [40, 40, 20]     # Больше прибыли на первых уровнях (в %)
  
  # Размер позиции
  position_sizing:
    method: "kelly_criterion"           # Математически обоснованный
    max_risk_per_trade: 0.5             # Консервативный подход
    correlation_adjustment: true        # Учет корреляций
    max_position_pct: 10.0              # макс 10% портфеля
  
  # Диверсификация
  max_concurrent_positions: 10
  max_positions_per_symbol: 1
  
  # Динамические параметры на основе волатильности
  volatility_adjustment:
    high_vol_threshold: 3.0
    low_vol_threshold: 1.5
    high_vol_multipliers: [1.8, 3.0, 5.0]
    low_vol_multipliers: [1.2, 2.0, 3.0]
    major_coins: ["BTCUSDT", "ETHUSDT", "BNBUSDT"]
    major_risk_multiplier: 1.0
    altcoin_risk_multiplier: 0.7
    meme_coin_risk_multiplier: 0.5

# Параметры торговли
trading:
  min_confidence_threshold: 0.65        # Торговать только при высокой уверенности
  max_positions: 5
  max_daily_trades: 15                  # Лимит для контроля качества
  rebalance_interval: "1h"
  multiframe_confirmation: true         # Требовать подтверждения от старших ТФ
  
# Параметры Bybit
bybit:
  fees:
    maker: 0.0002                       # 0.02%
    taker: 0.00055                      # 0.055%
    funding_rate: 0.0001                # ~0.01% каждые 8 часов
  slippage:
    base: 0.0005                        # 0.05% базовый slippage
    market_impact_threshold: 0.01       # 1% от часового объема

# Параметры бэктестирования
backtesting:
  initial_capital: 100000  # USD
  commission: 0.001        # 0.1%
  slippage: 0.0005        # 0.05%
  
  # Метрики для оценки
  metrics:
    - "total_return"
    - "sharpe_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"
    - "expectancy"
    - "calmar_ratio"

# Ансамбль моделей
ensemble:
  enabled: true
  models_count: 5
  voting_method: "weighted_average"  # или "unanimous"
  
  # Веса на основе производительности
  weight_metric: "sharpe_ratio"
  rebalance_frequency: "weekly"

# Логирование и мониторинг
logging:
  level: "INFO"
  handlers:
    - "console"
    - "file"
  
  # Путь для логов
  log_dir: "experiments/logs"
  
  # TensorBoard
  tensorboard:
    enabled: true
    log_dir: "experiments/tensorboard"
  
  # Weights & Biases
  wandb:
    enabled: false
    project: "crypto-ai-trading"
    entity: "your-entity"

# Производительность
performance:
  num_workers: 4          # для DataLoader
  device: "cuda"          # или "cpu"
  mixed_precision: true   # FP16 обучение
  
  # Кэширование
  cache_features: true
  cache_dir: "cache/"

# Валидация
validation:
  # Статистические тесты
  statistical_tests:
    - "sharpe_ratio_test"
    - "information_ratio"
    - "monte_carlo_permutation"
  
  # Минимальные требования
  min_sharpe_ratio: 1.5
  min_win_rate: 0.25      # для риска 1:3
  max_drawdown: 0.20      # 20%