backtesting:
  commission: 0.001
  initial_capital: 100000
  metrics:
  - total_return
  - sharpe_ratio
  - max_drawdown
  - win_rate
  - profit_factor
  - expectancy
  - calmar_ratio
  slippage: 0.0005
bybit:
  fees:
    funding_rate: 0.0001
    maker: 0.0002
    taker: 0.00055
  slippage:
    base: 0.0005
    market_impact_threshold: 0.01
data:
  end_date: '2025-06-16'
  interval_minutes: 15
  start_date: '2022-06-08'
  symbols:
  - BTCUSDT
  - ETHUSDT
  - BNBUSDT
  - SOLUSDT
  - XRPUSDT
  - ADAUSDT
  - DOTUSDT
  - LINKUSDT
  - AVAXUSDT
  - LTCUSDT
  test_ratio: 0.15
  train_ratio: 0.7
  val_ratio: 0.15
  walk_forward:
    step_size: 7
    test_window: 30
    training_window: 180
    validation_window: 30
database:
  database: ${DB_NAME:crypto_trading}
  host: ${DB_HOST:localhost}
  max_overflow: 20
  password: ${DB_PASSWORD:ruslan}
  pool_size: 10
  port: ${DB_PORT:5555}
  table: raw_market_data
  user: ${DB_USER:ruslan}
ensemble:
  enabled: true
  models_count: 5
  rebalance_frequency: weekly
  voting_method: weighted_average
  weight_metric: sharpe_ratio
features:
  cross_asset:
  - btc_dominance_effect
  - sector_correlation
  - lead_lag_signals
  microstructure:
  - bid_ask_spread
  - order_book_imbalance
  - volume_weighted_price
  - trade_flow_toxicity
  technical:
  - name: sma
    periods:
    - 10
    - 20
    - 50
  - name: ema
    periods:
    - 12
    - 26
  - name: rsi
    period: 14
  - fast: 12
    name: macd
    signal: 9
    slow: 26
  - name: bollinger_bands
    period: 20
    std_dev: 2
  - name: atr
    period: 14
  - bins: 20
    name: volume_profile
  temporal:
  - hour_of_day
  - day_of_week
  - month_of_year
  - is_weekend
logging:
  handlers:
  - console
  - file
  level: INFO
  log_dir: experiments/logs
  tensorboard:
    enabled: true
    log_dir: experiments/tensorboard
  wandb:
    enabled: false
    entity: your-entity
    project: crypto-ai-trading
model:
  activation: gelu
  batch_norm: true
  batch_size: 32
  context_window: 96
  d_ff: 512
  d_model: 256
  dropout: 0.1
  e_layers: 3
  early_stopping_patience: 10
  epochs: 100
  gradient_clip: 1.0
  individual: false
  input_size: 100
  learning_rate: 0.0001
  n_heads: 16
  name: PatchTST
  patch_len: 16
  pred_len: 4
  stride: 8
  warmup_steps: 1000
performance:
  cache_dir: cache/
  cache_features: true
  device: cuda
  mixed_precision: true
  num_workers: 4
remote_server:
  enabled: true
  key_path: ~/.ssh/vast_ai_key
  ports:
    jupyter: 8888
    tensorboard: 6006
    web_ui: 8080
  primary:
    host: 114.32.64.6
    port: 40134
  proxy:
    host: ssh3.vast.ai
    port: 33915
  python_path: /opt/conda/bin/python
  remote_path: /root/crypto_ai_trading
  sync:
    exclude:
    - cache/
    - '*.pyc'
    - __pycache__/
    - .git/
    - logs/
    - models_saved/
    - experiments/runs/
    - .DS_Store
  user: root
risk_management:
  max_concurrent_positions: 10
  max_positions_per_symbol: 1
  partial_close_sizes:
  - 40
  - 40
  - 20
  position_sizing:
    correlation_adjustment: true
    max_position_pct: 10.0
    max_risk_per_trade: 0.5
    method: kelly_criterion
  risk_reward_ratio: 3.0
  stop_loss_pct: 2.0
  take_profit_targets:
  - 1.5
  - 2.5
  - 4.0
  volatility_adjustment:
    altcoin_risk_multiplier: 0.7
    high_vol_multipliers:
    - 1.8
    - 3.0
    - 5.0
    high_vol_threshold: 3.0
    low_vol_multipliers:
    - 1.2
    - 2.0
    - 3.0
    low_vol_threshold: 1.5
    major_coins:
    - BTCUSDT
    - ETHUSDT
    - BNBUSDT
    major_risk_multiplier: 1.0
    meme_coin_risk_multiplier: 0.5
trading:
  max_daily_trades: 15
  max_positions: 5
  min_confidence_threshold: 0.65
  multiframe_confirmation: true
  rebalance_interval: 1h
validation:
  max_drawdown: 0.2
  min_sharpe_ratio: 1.5
  min_win_rate: 0.25
  statistical_tests:
  - sharpe_ratio_test
  - information_ratio
  - monte_carlo_permutation
