backtesting:
  commission: 0.001
  initial_capital: 100000
  metrics:
  - total_return
  - sharpe_ratio
  - max_drawdown
  - win_rate
  - profit_factor
  - expectancy
  - calmar_ratio
  slippage: 0.0005
bybit:
  fees:
    funding_rate: 0.0001
    maker: 0.0002
    taker: 0.00055
  slippage:
    base: 0.0005
    market_impact_threshold: 0.01
data:
  end_date: '2025-06-29'
  interval_minutes: 15
  start_date: '2020-03-25'
  symbols:
  - BTCUSDT
  - ETHUSDT
  - BNBUSDT
  - SOLUSDT
  - XRPUSDT
  - AAVEUSDT
  - ADAUSDT
  - ALGOUSDT
  - APEUSDT
  - APTUSDT
  - ARBUSDT
  - ATOMUSDT
  - AVAXUSDT
  - AXSUSDT
  - CAKEUSDT
  - DOGEUSDT
  - DOTUSDT
  - DYDXUSDT
  - ENAUSDT
  - ENSUSDT
  - FARTCOINUSDT
  - GALAUSDT
  - GMTUSDT
  - GRIFFAINUSDT
  - HBARUSDT
  - ICPUSDT
  - JTOUSDT
  - LDOUSDT
  - LINKUSDT
  - LTCUSDT
  - MELANIAUSDT
  - NEARUSDT
  - OMUSDT
  - ONDOUSDT
  - OPUSDT
  - 1000PEPEUSDT
  - PNUTUSDT
  - POPCATUSDT
  - SUIUSDT
  - TAOUSDT
  - TIAUSDT
  - TONUSDT
  - TRBUSDT
  - TRUMPUSDT
  - TRXUSDT
  - TWTUSDT
  - UNIUSDT
  - WIFUSDT
  - ZEREBROUSDT
  - 1INCHUSDT
  test_ratio: 0.2
  train_ratio: 0.6
  val_ratio: 0.2
  walk_forward:
    step_size: 7
    test_window: 30
    training_window: 180
    validation_window: 30
database:
  database: crypto_trading
  host: localhost
  max_overflow: 20
  password: ruslan
  pool_size: 10
  port: 5555
  table: raw_market_data
  user: ruslan
  # Альтернативное подключение через Unix socket (если TCP не работает)
  # unix_socket: /var/run/postgresql
ensemble:
  enabled: true
  models_count: 5
  rebalance_frequency: weekly
  voting_method: weighted_average
  weight_metric: sharpe_ratio
features:
  cross_asset:
  - btc_dominance_effect
  - sector_correlation
  - lead_lag_signals
  microstructure:
  - bid_ask_spread
  - order_book_imbalance
  - volume_weighted_price
  - trade_flow_toxicity
  technical:
  - name: sma
    periods:
    - 10
    - 20
    - 50
  - name: ema
    periods:
    - 12
    - 26
  - name: rsi
    period: 14
  - fast: 12
    name: macd
    signal: 9
    slow: 26
  - name: bollinger_bands
    period: 20
    std_dev: 2
  - name: atr
    period: 14
  - bins: 20
    name: volume_profile
  temporal:
  - hour_of_day
  - day_of_week
  - month_of_year
  - is_weekend
logging:
  handlers:
  - console
  - file
  level: INFO
  log_dir: experiments/logs
  tensorboard:
    enabled: true
    log_dir: experiments/tensorboard
  wandb:
    enabled: false
    entity: your-entity
    project: crypto-ai-trading
loss:
  name: unified_trading  # Унифицированная loss для 36 целевых переменных
  future_return_weight: 1.0  # Вес для future_return_1-4
  params:
    reduction: mean
    # Веса для различных компонентов
    direction_weight: 1.0
    tp_weight: 0.8
    sl_weight: 1.2
    entry_time_weight: 0.5
model:
  activation: gelu
  batch_norm: true
  batch_size: 1024  # МАКСИМАЛЬНО УВЕЛИЧЕН для RTX 5090
  context_window: 168  # 42 часа истории (168 * 15 минут)
  d_ff: 512  # Увеличен размер feedforward
  d_model: 256  # Установлено для соответствия fusion layer
  dropout: 0.15  # УМЕНЬШЕН для лучшего обучения в начале
  e_layers: 3  # Оптимальное количество слоев
  early_stopping_patience: 25  # УВЕЛИЧЕНО для терпения
  epochs: 100  # Максимум эпох для полного обучения
  gradient_clip: 1.0  # УВЕЛИЧЕН для стабильности
  individual: false
  input_size: 159  # Автоматически определено из данных
  learning_rate: 0.0001  # УМЕНЬШЕН для стабильности
  min_delta: 0.0001  # МЕНЕЕ чувствительный порог
  n_heads: 4
  name: UnifiedPatchTST  # ИЗМЕНЕНО на унифицированную модель
  output_size: 36  # ИЗМЕНЕНО для соответствия целевым переменным
  overfitting_threshold: 0.3  # МЕНЕЕ строгий контроль в начале
  patch_len: 16  # Увеличен размер патча
  use_amp: true      # Mixed Precision для RTX 5090
  amp_dtype: float16  # FP16 для совместимости с sm_120
  compile_model: false  # torch.compile отключен для совместимости
  use_tf32: true  # TensorFloat-32 для ускорения
  # Целевые переменные для торговой модели (36 переменных)
  target_variables:
    # Базовые возвраты
    - future_return_1
    - future_return_2
    - future_return_3
    - future_return_4
    # Long позиции
    - long_tp1_hit
    - long_tp1_reached
    - long_tp1_time
    - long_tp2_hit
    - long_tp2_reached
    - long_tp2_time
    - long_tp3_hit
    - long_tp3_reached
    - long_tp3_time
    - long_sl_hit
    - long_sl_reached
    - long_sl_time
    - long_optimal_entry_time
    - long_optimal_entry_price
    - long_optimal_entry_improvement
    # Short позиции
    - short_tp1_hit
    - short_tp1_reached
    - short_tp1_time
    - short_tp2_hit
    - short_tp2_reached
    - short_tp2_time
    - short_tp3_hit
    - short_tp3_reached
    - short_tp3_time
    - short_sl_hit
    - short_sl_reached
    - short_sl_time
    - short_optimal_entry_time
    - short_optimal_entry_price
    - short_optimal_entry_improvement
    # Направление и целевая переменная
    - best_direction  # LONG/SHORT/NEUTRAL
    - target_return_1h
  task_type: trading  # Специальный режим для торговли
  target_window: 1  # Предсказываем одно значение
  pred_len: 1  # Предсказываем одно значение
  stride: 8  # Увеличен шаг для меньшего перекрытия
  warmup_steps: 500  # Больше warmup шагов
  # Дополнительные параметры против переобучения
  label_smoothing: 0.0  # ОТКЛЮЧЕНО в начале обучения
  mixup_alpha: 0.0      # ОТКЛЮЧЕНО
  weight_noise: 0.0     # ОТКЛЮЧЕНО
  # Оптимизации для RTX 5090
  compile_model: false  # torch.compile не работает с sm_120
  use_tf32: true  # TensorFloat-32 для ускорения
  # Параметры для улучшенной версии PatchTST
  use_improvements: false  # Временно отключено до исправления размерностей
  feature_attention: true  # Использовать FeatureAttention
  multi_scale_patches: true  # Использовать многомасштабные патчи
optimizer:
  name: AdamW
  params:
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0.001
    amsgrad: true
performance:
  cache_dir: cache/
  cache_features: true
  data_parallel: true
  device: cuda  # RTX 5090 с 31.4 GB памяти
  mixed_precision: true  # Включено для RTX 5090
  num_workers: 4  # Оптимизировано для RTX 5090 - используем 4 воркера для загрузки данных
  persistent_workers: true  # Включаем для эффективности при num_workers > 0
  pin_memory: true
  prefetch_factor: 4  # Увеличено в 2 раза для предзагрузки
  gradient_accumulation_steps: 1  # Эффективный batch_size = 1024
remote_server:
  direct_connection:
    host: ssh1.vast.ai
    key_path: ~/.ssh/id_rsa
    port: 30421
    user: root
  enabled: true
  ports:
    jupyter: 8888
    tensorboard: 6006
    web_ui: 8080
  python_path: /opt/conda/bin/python
  remote_path: /root/crypto_ai_trading
  ssh_alias: vast-current
  sync:
    exclude:
    - cache/
    - '*.pyc'
    - __pycache__/
    - .git/
    - logs/
    - models_saved/
    - experiments/runs/
    - .DS_Store
risk_management:
  max_concurrent_positions: 10
  max_positions_per_symbol: 1
  partial_close_sizes:
  - 40
  - 40
  - 20
  position_sizing:
    correlation_adjustment: true
    max_position_pct: 10.0
    max_risk_per_trade: 0.5
    method: kelly_criterion
  risk_reward_ratio: 3.0
  stop_loss_pct: 2.0
  take_profit_targets:
  - 1.5
  - 2.5
  - 4.0
  volatility_adjustment:
    altcoin_risk_multiplier: 0.7
    high_vol_multipliers:
    - 1.8
    - 3.0
    - 5.0
    high_vol_threshold: 3.0
    low_vol_multipliers:
    - 1.2
    - 2.0
    - 3.0
    low_vol_threshold: 1.5
    major_coins:
    - BTCUSDT
    - ETHUSDT
    - BNBUSDT
    major_risk_multiplier: 1.0
    meme_coin_risk_multiplier: 0.5
scheduler:
  name: OneCycleLR  # ИЗМЕНЕНО для динамического LR
  params:
    max_lr: 0.001     # УМЕНЬШЕН максимальный LR для стабильности
    pct_start: 0.3   # 30% времени на разгон
    anneal_strategy: cos  # Косинусное затухание
    cycle_momentum: true
    base_momentum: 0.85
    max_momentum: 0.95
    div_factor: 25      # Начальный LR = max_lr / 25 = 0.00004
    final_div_factor: 10000  # Финальный LR = max_lr / 10000 = 0.0000001
trading:
  max_daily_trades: 15
  max_positions: 5
  min_confidence_threshold: 0.65
  multiframe_confirmation: true
  rebalance_interval: 1h
validation:
  max_drawdown: 0.2
  min_sharpe_ratio: 1.5
  min_win_rate: 0.25
  statistical_tests:
  - sharpe_ratio_test
  - information_ratio
  - monte_carlo_permutation
